### ISSUE TITLE
Can't open etc/wsl-terminal.conf for writing

### ISSUE THREAD

**Issue by joshglendenning** [goreliu/wsl-terminal#11]
I'm not sure what's going on, whether it's weird permissions or my machine, but for whatever reason I can't edit `etc/wsl-terminal`. Vim says it "Can't open file for writing", and Notepad++ says "Please check if this file is opened in another program". Does wsl-terminal start some daemon that holds these files open?

**Comment by goreliu** [comment]
wsl-terminal doesn't hold these files. I haven't met this problem, maybe wsl-terminal.conf is opened in other programs.

**Comment by joshglendenning** [comment]
It's been a while and I don't think I've seen this issue since Oct 4, so I'm gonna go ahead and close this.
