### ISSUE TITLE
Windows Clipboard <-> Linux Clipboard

### ISSUE THREAD

**Issue by dakom** [goreliu/wsl-terminal#111]
Is it possible to somehow have them be the same thing?

Specifically, I want to be able to do this from vim in wsl-terminal: `"+y` and then paste the contents on the windows host side. Alternatively, copy something from a browser in the windows host side, and paste it into Vim via `"+p`

**Comment by libratwo** [comment]
1. like in real linux distribution(ubuntu etc.), default system vim is not support clipboard(vim --version)

**Comment by libratwo** [comment]
need to solve:like in real linux distribution(ubuntu etc.), default system vim is not support clipboard(vim --version)

**Comment by dakom** [comment]
I ended up solving it by switching to Neovim, which has a solution using w32yank :)

Works perfectly :D

Closing this for now - thanks!

**Comment by libratwo** [comment]
this would be great ;)
