### ISSUE TITLE
How to make the terminal's path in /root when I open it ?

### ISSUE THREAD

**Issue by ontheway1215** [goreliu/wsl-terminal#113]
When i open the terminal ,it path is too long,just like this 
![image](https://user-images.githubusercontent.com/11936847/42639812-7d1684c2-8623-11e8-8f03-99916c03b488.png)
I just want it can be like this
![image](https://user-images.githubusercontent.com/11936847/42640716-7893e6a4-8625-11e8-9c44-f9fb502621ee.png)
when i open it first

**Comment by jaredparkinson** [comment]
There is a shell script that lives at ~/.bashrc that is run when you open a terminal window. You can add a line in there to cd into the root folder. The ~/.bashrc file needs to be opened inside the Linux environment itself, and not in Windows.  `nano ~./bashrc` will work if you haven't installed any other text editors, like vim. Whatever editor you choose, add the follow line to the end of the file:
`cd /`
Now the next time you open the terminal you should be at the root directory.

**Comment by szthanatos** [comment]
Just add '-C ~' args in your shortcut's target.
