### ISSUE TITLE
Cannot run open-wsl.exe under some conditions relating to space in path

### ISSUE THREAD

**Issue by martixingwei** [goreliu/wsl-terminal#12]
This error can be reproduced by the following steps:
1. Create a folder which name contains space, such as `C:\folder name\`
2. Put whole `wsl-terminal` folder under the folder created in step 1
3. Create a file named the same as the first half (before first space) of the folder name from step 1 and put them under the same path, such as `C:\folder`
4. Try to run `C:\folder name\wsl-terminal\open-wsl.exe` and you will get the error

**Comment by goreliu** [comment]
I fixed it in [v0.6.6](https://github.com/goreliu/wsl-terminal/releases/tag/v0.6.6).
