### ISSUE TITLE
wsl-terminal opens and then immediate crashes. How can I debug?

### ISSUE THREAD

**Issue by gobengo** [goreliu/wsl-terminal#123]
I've been using wsl-terminal for a couple months now with no issues. Thanks for making it!

But today I clicked to open it. The terminal window opens briefly, then immediately closes. I don't believe there is ever a bash prompt or errors in the terminal.

I tried
* running without `~/.bash*` files, in case my config was screwing something up. But same behavior.
* Downloading wsl-terminal again and running from a new directory. Same behavior.

FWIW running WSL from the official windows Debian App works fine. So does wslbridge.

Any ideas? How would I go about even debugging this to see what's wrong?
Other than in the wsl-terminal directory I unzip and run things from, is there any other app data that I should try to clear out?

**Comment by gobengo** [comment]
For some reason, my `/mnt/c/` drive was not mounted in WSL.
I re-mounted it (using Debian WSL app) using this command: https://github.com/Microsoft/WSL/issues/1864#issuecomment-392350563

After that, wsl-terminal opens all good.

**Comment by thiagotalma** [comment]
I'm having the same immediate shutdown problem.

However, everything is ok with /mnt/c

How did you manage to debug?
