### ISSUE TITLE
How to avoid mouse scrolling?

### ISSUE THREAD

**Issue by oblitum** [goreliu/wsl-terminal#13]
I have a touchpad by which I trigger mouse scrolling by accident with some frequency. On Linux I can configure tmux with the following to disable mouse scrolling:

```
# Avoid scrolling through command history and what not.
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'
```

It has no effect on wsl-terminal. Is there a setting to disable mouse scrolling on mintty, or simply disable mouse at all?

**Comment by oblitum** [comment]
Correction, the command may indeed have the effect of avoiding scrolling through command history, the issue I have actually is that mouse scrolling still scrolls the window like if using the scrollbar.

**Comment by goreliu** [comment]
Running a [AHK](http://autohotkey.com/) script may work:

```
#NoEnv
Hotkey, IfWinActive, ahk_class mintty
Hotkey, WheelUp, pass
Hotkey, WheelDown, pass

pass:
return
```

**Comment by oblitum** [comment]
@goreliu thanks for the response, though I'd prefer it was built into the emulator itself... You may close the issue if you feel it's out of scope.
