### ISSUE TITLE
Fails to start when setting WLinux as default

### ISSUE THREAD

**Issue by jason404** [goreliu/wsl-terminal#136]
I had wsl-terminal working fine with kali-linux, but I use WLinux as my main WLS distro. After setting the default using `wslconfig /setdefault WLinux`, wsl-terminal closes immediately after starting.  ie, As soon as I start it (using Start Menu icon or open-wsl.exe, the window appears for a few millisrconds and then disappears.  Reverting to kali-linux as default and it works fine.

Is there any reason why this doesn't work with WLinux?

**Comment by jason404** [comment]
WLinux mounts root at /, so wsl-terminal it cannot find wslbridge-backend on startup.

**Comment by mcfiredrill** [comment]
Is there a way to use wsl-terminal if root is mounted at / ?

**Comment by jason404** [comment]
I don't know, but I seem to have WLinux root mounted at / and working fine with wsltty on this machine I am using at the moment.  Try wsltty, which is another mintty fork.
