### ISSUE TITLE
can not use 'zsh' after changing default shell

### ISSUE THREAD

**Issue by tdkihrr** [goreliu/wsl-terminal#139]
After I changing the default shell to 'zsh' by using 'chsh' command, wsl-open didn't use 'zsh' as default shell. 

When I opened 'open-wsl', it still used 'bash' not 'zsh'.

-----info-----
wsl system version: ubuntu 18.04
windows system version: 1803 17134.472
open-wsl version: 0.8.12

**Comment by mmdaminmlz** [comment]
i have this problem, also.
when i start wsl from cmd or start menu, my shell is /usr/bin/fish but wsl-terminal still uses /usr/bin/bash

**Comment by tdkihrr** [comment]
thx, I will try it.

**Comment by tdkihrr** [comment]
> you need to edit SHELL variable in file etc\wsl-terminal.conf

Thx, I will try it.
