### ISSUE TITLE
tmux resurrect

### ISSUE THREAD

**Issue by krzysztofantczak** [goreliu/wsl-terminal#14]
Hey,

Any ideas how can we hook things up with https://github.com/tmux-plugins/tmux-resurrect? I was trying to play with it a bit, but the main issue was that #{pane_current_path} is always empty while exporting tmux current windows/panes state. I was trying wsl-terminal + tmux 2.1 up to 2.4 and various changes in save.sh script but the result (despite people telling their success stories on OSX and Linux) was exactly the same. So i figured, perhaps it has something to do with the way it works under wsl-terminal? I think this project deserves a way to store and restore opened windows and this tmux plugin seems to be pretty good choice for it.

https://github.com/tmux-plugins/tmux-resurrect/blob/master/scripts/save.sh#L44 - this is the place responsible for storing current PATH for pane.

Also, the way i was running tmux (use_tmux=0/1 and running tmux by hand or by terminal - also with attach_tmux_locally) has no effect.

Any ideas? Any hints?

**Comment by goreliu** [comment]
Sorry for no reply for a long time. tmux-resurrect should work well now.
