### ISSUE TITLE
Missing virtual desktop support.

### ISSUE THREAD

**Issue by qis** [goreliu/wsl-terminal#15]
The software forces a virtual desktop switch and opens it's window on the wrong desktop when another window already exists.

**Comment by goreliu** [comment]
Sorry, I don't kown how to support it.

**Comment by qis** [comment]
@goreliu Let me speculate: When the user starts the application, it uses IPC to instruct an existing process to create a new window.

I apologise for not fixing it myself. No time and wsltty works really well.

**Comment by goreliu** [comment]
wsl-terminal is just a starter of mintty, has no it's own process, so it's difficult to support it.

Or you can set use_tmux=0 in etc/wsl-terminal.conf, then each time a new mintty will be started.
