### ISSUE TITLE
Is it possible to open wsl in the specified windows directory?

### ISSUE THREAD

**Issue by zeng-xs** [goreliu/wsl-terminal#16]

**Comment by goreliu** [comment]
`cd xxx & /path/to/open-wsl.exe`

**Comment by ElTopo** [comment]
How about a directory in lxfs, for example, user's $HOME (~)? wslbright has an option -C WSLDIR so you can pass ~, see
https://github.com/rprichard/wslbridge/blob/master/frontend/wslbridge.cc

**Comment by goreliu** [comment]
I added a [-C dir](https://github.com/goreliu/wsl-terminal/commit/5137fd3afa5a2bf5c6d94fcefc3b451c95f97904) option.

**Comment by BetterLuke** [comment]
Hi, how to use -C dir command? I input it on CMD, but open open-wsl window directly.

**Comment by joiharalds** [comment]
@BetterLuke In a console, cmd e.g., you do:

open-wsl.exe -C ~

This feature has not been added to v0.6.9 which is the most recent version available for download as executables. So you have to build from source, https://github.com/goreliu/wsl-terminal#build.
This feature is very neat to use in a AutoHotKey script.

**Comment by BetterLuke** [comment]
I had changed my zshrc file  to solve it. But also realy thanks.

**Comment by rosuH** [comment]
@BetterLuke I created a `launch.bat` file including these command:
```
open-wsl.exe -C "/mnt/d/Documents/"
```
So it can open in `D:\Documents`.
- - - - -
In WSL, `D:\Documents`  was mounted in `/mnt/d/Documents`.
