### ISSUE TITLE
Fails to launch in Window 10 Insider preview 14986

### ISSUE THREAD

**Issue by twisterghost** [goreliu/wsl-terminal#17]
I'm seeing behavior on my laptop (Surface book 1 running insider build 14986.rs_prerelease.161202-1928) where upon trying to launch, it hangs explorer, and never launches. I'm not seeing this behavior on my desktop, running the current windows 10 build (14393.693)

I don't get an error message or anything, it just never launches. I am able to open the normal WSL command line and it runs fine.

**Comment by goreliu** [comment]
I can't guess the reason, maybe you can try [wsltty](https://github.com/mintty/wsltty).

**Comment by twisterghost** [comment]
Yeah, I know this is not a lot to go on. Just wanted to report what I saw given that this build is coming down the line. Might be fixed by the time it hits stable, though.

**Comment by lizy14** [comment]
It seems to relate to __SmartScreen__. Try to disable it.

**Comment by twisterghost** [comment]
Yeah after the latest insider build, I'm getting the smartscreen popup. Will look into disabling it.
