### ISSUE TITLE
Using -l parameter doesn't execute .bashrc file

### ISSUE THREAD

**Issue by matracey** [goreliu/wsl-terminal#19]
I'm trying to create a shortcut that will open the terminal in my WSL home directory, so I'm using the -l switch. However, when I use this switch, the terminal doesn't seem to execute my .bashrc file. 

**Started with the -l parameter:**
![image](https://cloud.githubusercontent.com/assets/1207505/22374983/3b268286-e4a0-11e6-9d97-b1de9f3d4ee0.png)

**Started without the -l parameter:**
![image](https://cloud.githubusercontent.com/assets/1207505/22374963/2a506526-e4a0-11e6-8fbe-a08b7f78f4d5.png)

**Comment by goreliu** [comment]
You can write this line to ~/.bash_profile:

```
[[ -f ~/.bashrc ]] && . ~/.bashrc
```
