### ISSUE TITLE
"Open WSL here" context menu appears on recycle bin

### ISSUE THREAD

**Issue by jantari** [goreliu/wsl-terminal#20]
Tested on Windows 10 Build 14393.693 (production) and Windows 10 Build 15025.1000 (Insider) with wsl-terminal 0.6.6

By default after setting up the "Open WSL here" context menu entry, it attaches itself to the Recycle bin context menu. Clicking it opens the WSL Terminal to the desktop.

**Comment by goreliu** [comment]
I don't kown how to remove the context menu entry from the Recycle bin context menu.

**Comment by goreliu** [comment]
I fixed it in [v0.8.0](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.0).

Remove the old menu first, and run `tools/1-add-open-wsl-terminal-here-menu.js`.
