### ISSUE TITLE
`open-wsl.exe -l` does not work with `shell=bash -c "zsh"`

### ISSUE THREAD

**Issue by zzh1996** [goreliu/wsl-terminal#22]
wsl-terminal.conf :
```
shell=bash -c "zsh"
```

When I run `open-wsl.exe -l`, wsl-ternimal opens in current directory, not home directory.

It works correctly without `-c "zsh"`

**Comment by goreliu** [comment]
You can set shell to zsh or /path/to/zsh.

**Comment by zzh1996** [comment]
no matter what shell you set as your default, you can only start WSL by typing `bash` in CMD and bash will run.

**Comment by goreliu** [comment]
It has no matter with CMD.

**Comment by zzh1996** [comment]
problem solved
