### ISSUE TITLE
Can not save my option after I clicked Apply instead of Save

### ISSUE THREAD

**Issue by niuguangyu** [goreliu/wsl-terminal#26]
Hi, this is the first time I use this terminal. I applied the option I modified in option menu and reopened the terminal, ``NOTHING`` had been changed. And I found that ``Apply`` can not save my option and I should use the ``Save`` button.  
This may be a bug. I hope this terminal can be better.

**Comment by goreliu** [comment]
`Apply` will not save options to files.
