### ISSUE TITLE
Can I use wsl-terminal directly?

### ISSUE THREAD

**Issue by Po-wei** [goreliu/wsl-terminal#27]
Windows' recently update--WSL  is just awesome
I had run into some color-theme issues until I found this one
It support full 256-color and abundant color theme!

However, i found it automatically open some tools such as wslbridge
![image](https://cloud.githubusercontent.com/assets/17596021/25563744/1b2c8b5a-2dd5-11e7-9eb8-a915e9943fb9.png)
Is it possible to luach shell directly like the upper one which is lunched by default icon ?

**Comment by sunjoong** [comment]
@Po-wei - Oh, I see you again. You SHOULD use wslbridge to use these programs.
> wslbridge is a Cygwin program that allows connecting to the WSL command-line environment over TCP sockets, as with ssh, but without the overhead of configuring an SSH server. -- https://github.com/rprichard/wslbridge

These console utilies are not linux programs, but cygwin program (in this case) or msys2 program. Those connect to WSL with TCP socket, so you should run backend program in WSL.

**Comment by Po-wei** [comment]
@sunjoong  LOL, the world is small!
Thanks for your explanation!
