### ISSUE TITLE
Support for clickable links

### ISSUE THREAD

**Issue by josteink** [goreliu/wsl-terminal#28]
We often get links in our terminals (stuff from tooling, build output, irc, whatever).

Having links rendered to be clickable would be a nice addition.

**Comment by goreliu** [comment]
`Ctrl + Click` can open a link(such as http://example.org or /mnt/c/test.txt).

**Comment by josteink** [comment]
Oh my. Now I feel stupid. (I honestly *tried* shift-click at least)

Thanks for clearing that up.

Maybe that could be something to consider adding to the keyboard/config section in the readme, for increased visibility?
