### ISSUE TITLE
multi tab support

### ISSUE THREAD

**Issue by zhangnew** [goreliu/wsl-terminal#29]
I hope use multi tab in a Window, instead of open many terminal with many Window.

I tried Tmux, but failed.

**Comment by Victor-Savu** [comment]
What exactly didn't work when you tried tmux?

**Comment by goreliu** [comment]
https://github.com/mintty/mintty/issues/8

**Comment by zhangnew** [comment]
@Victor-Savu I use ArchLinux in wsl, when I try to start tmux, err:
```
tmux: invalid LC_ALL, LC_CTYPE or LANG
```
But I can't set my `locale` LANG, it's a wsl bug.

**Comment by Victor-Savu** [comment]
@zhangnew thanks for the clarification! I suppose you tried fixing the locale problem:
https://www.google.de/amp/s/amp.reddit.com/r/bashonubuntuonwindows/comments/65e36z/psa_localegen_is_bugged_solution_extract_the/

**Comment by zhangnew** [comment]
@Victor-Savu thanks for your solution,I tried, but not resolved.
```
bison: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.
```
it's another bug. https://github.com/Microsoft/BashOnWindows/issues/1878

I give up. I plan to reinstall my os with Arch Linux.

**Comment by goreliu** [comment]
You can copy a `/usr/lib/locale/locale-archive` from an archlinux os.

**Comment by goreliu** [comment]
I built a tabed version based on  [fatty](https://github.com/paolo-sz/fatty), [v0.8.11](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.11).

![fatty](https://user-images.githubusercontent.com/169704/39105741-27dd21fa-46ea-11e8-80fc-032375b6f2d4.png)

**Comment by fatfatson** [comment]
@goreliu how to change tab's title?
btw: I'd like to set title to corresponding hostname, that is also why I need tab even with tmux,  it's hard to control multi nest tmux.
