### ISSUE TITLE
New tmux window on opening wsl-terminal.

### ISSUE THREAD

**Issue by mateuszlewko** [goreliu/wsl-terminal#31]
I've enabled `use_tmux` option and `attach_tmux_locally` and it works great aparat from fact that every time I reopen wsl-terminal windows it creates additional windows in my current tmux sessions.

Is this an intended behavior? Can I do something so it won't open new window in tmux on startup?

**Comment by goreliu** [comment]
I use use_tmux and attach_tmux_locally, then add thess lines to .zshrc:

```
[ -z "$TMUX" -a -n "$USE_TMUX" ] && {
    [ -n "$ATTACH_ONLY" ] && {
        tmux a 2>/dev/null || {
            cd && exec tmux
        }
        exit
    }

    tmux new-window -c "$PWD" 2>/dev/null && exec tmux a
    exec tmux
}
```

No additional windows will created by tmux.
