### ISSUE TITLE
[Feature] Copy and paste hotkeys

### ISSUE THREAD

**Issue by thenets** [goreliu/wsl-terminal#32]
Will be an awesome feature copy with Ctrl+Shift+C and paste with Ctrl+Shift+V.

**Comment by thenets** [comment]
I found the option in the menus! Sorry.

**Comment by gfsd3v** [comment]
@thenets how did u did it ? can't find this option

**Comment by thenets** [comment]
@gfsd3v I don't remember :/ now I'm using the Windows Terminal Beta
