### ISSUE TITLE
[Feature] Presets based on mainly terminals

### ISSUE THREAD

**Issue by thenets** [goreliu/wsl-terminal#33]
In the menus, will be great show presets based on main terminals and/or distros.

Example: at the first app start, popup a window with big buttons with logos of Ubuntu, Mint, Gnome and KDE. Based on this option, all settings will be set.

**Comment by goreliu** [comment]
Sorry, I won't support this feature, maybe you can post here(https://github.com/mintty/wsltty/issues).
