### ISSUE TITLE
Blank Terminal on Launch

### ISSUE THREAD

**Issue by jbawgs** [goreliu/wsl-terminal#35]
Not sure what I'm missing here.

If I launch open-wsl.exe via explorer or run command, I get nothing but a cursor and no functionality.
If I launch from cmd prompt, it works as expected. Any insights?

EDIT: Success condition is actually running open-wsl as admin.

**Comment by goreliu** [comment]
https://github.com/goreliu/wsl-terminal/issues/36#issuecomment-329681075
