### ISSUE TITLE
Starts but closes immediately...

### ISSUE THREAD

**Issue by sixro** [goreliu/wsl-terminal#36]
If I execute open-wsl.exe (even as administrator), it starts showing a window for very few ms, then close immediately.
The lsb_release shows:
 No LSB modules are available.
 Distributor ID: Ubuntu
 Description:    Ubuntu 14.04.5 LTS
 Release:        14.04
 Codename:       trusty

**Comment by codeman38** [comment]
Looks like this may be related to wslbridge 0.2.2, which is incompatible with the kernel from 14.04.

**Comment by Puharesource** [comment]
@codeman38 That doesn't seem to fix the issue, I just tried replacing `wslbridge.exe` and `wslbridge-backed` in the bin directory, but the terminal still flashes too fast to see what the issue is.

**Comment by Victor-Savu** [comment]
@sixro could you please post your configuration file for wsl-terminal? Also, are you using tmux? I had this issue as well and the problem was that I had misconfigured my  shell configuration script (.zshrc in my case) so it was calling exit one too many times :)

**Comment by sixro** [comment]
Hi Victor, I do not have any custom configuration... I installed wsl-terminal and I tried to start it using open-wsl.exe

**Comment by Victor-Savu** [comment]
@sixro ok, that is indeed problematic :) does the windows bash terminal work?

**Comment by sixro** [comment]
Hi @Victor-Savu, yes the windows bash terminal works...

**Comment by DeGuitard** [comment]
I have the same issue.

**Comment by goreliu** [comment]
This issue seems to be fixed after v0.6.11.

**Comment by sixro** [comment]
Hi @goreliu, I confirm that now it works.
I downloaded again the 0.8.1 anyway to make this test.
