### ISSUE TITLE
How to set the default directory to the "~",not the "/mnt/d/wsl-terminal" instead ?

### ISSUE THREAD

**Issue by CuriousFu** [goreliu/wsl-terminal#37]
i just want to enter the "~" when i run the wsl-terminal , who can show me how ? A lot of thanks if anyone could offer help.

**Comment by goreliu** [comment]
Create a .lnk file to open-wsl.exe, and motify target to `D:\wsl-terminal\open-wsl.exe -C ~` .

**Comment by CuriousFu** [comment]
Thank you so much ,it rellay works. @goreliu

**Comment by oblitum** [comment]
@goreliu this doesn't work for me, it always starts at the directory that's set in the "Start in" option of the .lnk file.

**Comment by paulo6** [comment]
According to the readme, the -l argument to open-wsl.exe is what you are after:
"-l: ignores current path and starts terminal in your home directory (doesn't work with tmux)."

I have tried this and it works for me!

**Comment by oblitum** [comment]
Sadly I'm tmux addict...

**Comment by oblitum** [comment]
@paulo6 the `-l` did work for me thanks, even with the tmux setup I use (which is not related to `wsl-terminal` options).
