### ISSUE TITLE
add-open-wsl-here-menu.js syntax error

### ISSUE THREAD

**Issue by dlynch29** [goreliu/wsl-terminal#38]
Hi there, when I run  `tools/add-open-wsl-here-menu.js` as per the readme, I get the following error:

> tools/add-open-wsl-here-menu.js: line 1: syntax error near unexpected token \`('
> tools/add-open-wsl-here-menu.js: line 1: `var WshShell = new ActiveXObject("WScript.Shell");'

**Comment by goreliu** [comment]
Double click it.

**Comment by dlynch29** [comment]
That did it! Thanks.

**Comment by fernandoxu** [comment]
一样的问题，双击哪里啊?JS文件？

**Comment by zhouchongchong** [comment]
when i double clicked it, this file is open in edit

**Comment by zhouchongchong** [comment]
> 一样的问题，双击哪里啊?JS文件？

我刚刚解决了，第一修改默认程序为微软默认的Microsoft windows based script host，然后参考下面两个网页 https://jingyan.baidu.com/article/ff42efa93a7ad9c19e2202f0.html https://zhidao.baidu.com/question/618962866361761572.html

**Comment by Dmi3Iva** [comment]
Hint: execute with Windows Script Host (WSH).
