### ISSUE TITLE
Cannot open multiple mintty instances

### ISSUE THREAD

**Issue by hannahjherself** [goreliu/wsl-terminal#39]
Hi

I would like to be able to run multiple tmux sessions in multiple instances of mintty with wsl-terminal. Whenever I try to run open-wsl a second time either from the start menu shortcut or the app directory itself, I get the error:

Failed to run '/bin/bash': No such file or directory

And when I press a key the mintty windows.

I can open multiple mintty windows with other versions of mintty I have on my PC.

Any idea how I could get this to work?

**Comment by goreliu** [comment]
You can set `use_tmux=0` in `etc/wsl-terminal.conf`, and run `open-wsl -c tmux`.
