### ISSUE TITLE
Tries to open a back door

### ISSUE THREAD

**Issue by eastrader** [goreliu/wsl-terminal#40]
On installation I found it tried to set up a back door to the internet, some place. My inplace software blocked it. Why does it need a back door to the internet?

**Comment by goreliu** [comment]
The Windows program `bin/wslbridge.exe` keeps a TCP connection with the WSL program `bin/wslbridge-backend`, like ssh client and ssh server. More  details ([here](https://github.com/rprichard/wslbridge/issues/3#issuecomment-248186713)).
