### ISSUE TITLE
Enable wscript to install context menu open with vim

### ISSUE THREAD

**Issue by atgiovannini** [goreliu/wsl-terminal#42]
could be nice to have wscript for install "open in vim" for all files in the context menu like Sublime or Visual studio codes do when install.

**Comment by goreliu** [comment]
I added `5-add-open-with-vim-menu.js` and `5-remove-open-with-vim-menu.js` (https://github.com/goreliu/wsl-terminal/commit/9af58efda5db6e7919c4f3d9a0ac99bba1767808).
