### ISSUE TITLE
midnight commander shell window does not work

### ISSUE THREAD

**Issue by vadim-ag** [goreliu/wsl-terminal#46]
wsl-terminal: v0.8.3
mintty: 2.7.9
midnight commander: 4.8.15 (apt-get installed)
Windows 10: build 1703 (wsl / ubuntu)

When shell window opened (`Ctrl-O`) no shell prompt. Any key causes return to normal (blue panel) window.

Expected: shell

For comparison, cygwin64, mintty 2.7.4, and mc 4.8.18 do not have this issue.

**Comment by vadim-ag** [comment]
I verified with wsl-terminal v0.7.0 (which builds with mintty 2.7.4). The same effect.

**Comment by vadim-ag** [comment]
Even more interesting: when `mc` started as a root (`sudo mc`) the shell works as expected.

**Comment by goreliu** [comment]
I run mc 4.8.19 in Windows 10 build 1709, it works well.

What will happen if you run mc in bash.exe?

**Comment by vadim-ag** [comment]
When I am running `mc` in windows terminal (`win-R`, `bash.exe`) I do not have this problem. It looks limited to `wsl-terminal`.

**Comment by goreliu** [comment]
I installed Ubuntu from Win Store and run mc 4.8.15, it works well.

I don't have a Windows 10 build 1703 environment, so I don't know how to find out the reason.

**Comment by goreliu** [comment]
Remove these lines from ~/.bashrc:

```
case $- in
    *i*) ;;
      *) return;;
esac
```

**Comment by goreliu** [comment]
Set `shell` in `etc/wsl-terminal.conf` to `/bin/bash` may work.

**Comment by vadim-ag** [comment]
> Set shell in etc/wsl-terminal.conf to /bin/bash may work.

It works! Thank you very much. I will submit a PR.

**Comment by issidzbrsk** [comment]
mc -X
alias mc="mc -u -X"

**Comment by xparq** [comment]
@issidzbrsk, what is `-X`? `mc --help` fails to mention that one. And so does its [man page](https://linux.die.net/man/1/mc).

**Comment by ennorehling** [comment]
-X is apparently short for --no-X11 (on my system, the man page lists it)
