### ISSUE TITLE
[suggestion] add tabs

### ISSUE THREAD

**Issue by davidcoleman007** [goreliu/wsl-terminal#48]
support tabs in the terminal similar to other terminal programs.  I have not found a good solution for this.

**Comment by goreliu** [comment]
See also https://github.com/goreliu/wsl-terminal/issues/29

**Comment by SanchezAta** [comment]
Yes, this feature is more important for me. While, could you provide a temporal solution for split tabs with a configuration file of tmux or something like this? In the other hand, what is the way for add tabs with other solutions?

**Comment by SanchezAta** [comment]
This command prompt is clean and beautiful. Please, continue make a great program, beautiful and clean with a many big tooling integrated.

**Comment by abalter** [comment]
This is very important for me.

I would like to help. Can you give me a hint of where to start with the code. Is this an electron app?

**Comment by goreliu** [comment]
@abalter https://github.com/mintty/mintty/issues/8 may help.

**Comment by abalter** [comment]
That's awesome!

**Comment by goreliu** [comment]
@abalter Download [wsl-terminal-tabbed-0.8.11.7z](https://github.com/goreliu/wsl-terminal/releases/download/v0.8.11/wsl-terminal-tabbed-0.8.11.7z), right click the black area.
