### ISSUE TITLE
Unable to open with right

### ISSUE THREAD

**Issue by bitqiang** [goreliu/wsl-terminal#49]
![image](https://user-images.githubusercontent.com/13163400/31700946-4b2bcb30-b3ff-11e7-9a27-b645079a81b2.png)

![image](https://user-images.githubusercontent.com/13163400/31700949-52a71d1a-b3ff-11e7-990b-d9cd147a3a65.png)

I don't know where to set it up, okay? I've installed WSL

**Comment by necan** [comment]
you can try easy context menu, it’s easy to add right context menu.

**Comment by goreliu** [comment]
运行 `1-add-open-wsl-terminal-here-menu.js` 之后移动过 `wsl-terminal` 目录吗（如果移动过需要重新运行一下），或者所在路径有没有带中文和空格的目录名（不支持同时带中文和空格的目录名）？

**Comment by bitqiang** [comment]
咦。。突然可以了。是不是需要重启电脑啥的

**Comment by bitqiang** [comment]
0.0 但是我现在这套电脑又不行。。你们都没遇见过这种问题吗？

**Comment by goreliu** [comment]
每次开机后过一阵就不能用了，还是什么情况？

**Comment by bitqiang** [comment]
不是每次开机。是我两台电脑，一样的配置。。有台电脑就不能右键。。
不过我现在使用的是clover。能把他放到书签栏，这样也可以使用。

**Comment by goreliu** [comment]
运行 `1-add-open-wsl-terminal-here-menu.js` 之后移动过 `wsl-terminal` 目录吗（如果移动过需要重新运行一下），或者所在路径有没有带中文和空格的目录名（不支持同时带中文和空格的目录名）？

**Comment by bitqiang** [comment]
0.0 没有的。也不知道为啥。。路径是这样的
![image](https://user-images.githubusercontent.com/13163400/31817489-bf0d4038-b5c6-11e7-87ff-8dd65ca2e028.png)

**Comment by goreliu** [comment]
重新运行下 `1-add-open-wsl-terminal-here-menu.js` 呢？

**Comment by bitqiang** [comment]
0.0  运行了。。感觉两台电脑环境差不多，这台电脑就是不行。。会不会wsl的问题。

**Comment by bitqiang** [comment]
刚刚看了我的win10版本是 15063。另一台是1703的然后它就可以用。有可能是win10版本的问题？

**Comment by goreliu** [comment]
找不到应用程序那个错误的话，和版本没关系。提供的信息太少，没法判断。

**Comment by bitqiang** [comment]
直接运用的可以的，就是右键有问题。。而且我发现这台电脑在wsl里面开的服务，windows都访问不到。。我都把wsl卸载重装好几回了。。

**Comment by goreliu** [comment]
可以贴下 cmd 里运行的 `reg query HKEY_CURRENT_USER\Software\Classes\Directory\shell\open-wsl\command` 命令结果，我看下有没有问题。

另外因为我不知道你环境的具体问题，很难查，也许你可以升级 Windows 试试。

**Comment by goreliu** [comment]
先关了，应该是系统环境的问题，如果能提供更多细节可以再打开。

**Comment by huyinjie** [comment]
我遇到了同样的问题，原因应该是把wsl-terminal这个文件夹放在了C盘，解决办法如下：
1. 换一个不要管理员权限的目录放，例如”文档“
2. 右键点击文件夹“安全”-”高级“-修改所有者，并在“安全”选项框下给与"System"和当前用户所有权限

**Comment by bitqiang** [comment]
谢谢啦。我有空试试

**Comment by qins** [comment]
右键，选择运行有问题。修改为默认wscript执行后，双击。搞定！
