### ISSUE TITLE
Add a parameter to open-wsl.exe for opening your home directory

### ISSUE THREAD

**Issue by QuiZr** [goreliu/wsl-terminal#5]
I'd like to create an shortcut to open-wsl.exe that will open /home/user directory. I know that I can just cd in .zshrc or something but a parameter would be a great way to do it.

**Comment by goreliu** [comment]
I added a -l param to open-wsl.exe (https://github.com/goreliu/wsl-terminal/commit/1b1b74b85f54dafb57c999e4c46bf0e756a96a96), but it only works when use_tmux=0 (in etc/wsl-terminal.conf). If use_tmux=1, when I try doing this, tmux will hang like https://github.com/goreliu/wsl-terminal/issues/1.

**Comment by QuiZr** [comment]
Thanks! :smile:
