### ISSUE TITLE
How can I use sz/rz in wsl-terminal?

### ISSUE THREAD

**Issue by XhinLiang** [goreliu/wsl-terminal#50]
How can I use sz/rz in wsl-terminal ( as a client )?

**Comment by goreliu** [comment]
You can try [zssh](http://zssh.sourceforge.net/) or [ckermit](http://www.kermitproject.org/).

**Comment by XhinLiang** [comment]
Zssh is as old as my grandma...

**Comment by goreliu** [comment]
I closed it, reopen it if needed.
