### ISSUE TITLE
Solarized themes are buggy

### ISSUE THREAD

**Issue by mintty** [goreliu/wsl-terminal#52]
ANSI colours 10, 11, 12 and 14 of the solarized themes are almost grey, not coloured.
(mintty/mintty#683)

**Comment by goreliu** [comment]
The solarized themes in [iamthad/base16-mintty](https://github.com/iamthad/base16-mintty) seem ok:

https://github.com/iamthad/base16-mintty/blob/master/mintty/base16-solarized-dark.minttyrc

```
BoldGreen=7,54,66
BoldYellow=88,110,117
BoldBlue=131,148,150
BoldCyan=211,54,130
```

![dark](https://user-images.githubusercontent.com/169704/31974525-cfa0b9c0-b95e-11e7-8975-72f23189dadf.png)

https://github.com/iamthad/base16-mintty/blob/master/mintty/base16-solarized-light.minttyrc

```
BoldGreen=238,232,213
BoldYellow=147,161,161
BoldBlue=101,123,131
BoldCyan=211,54,130
```

![light](https://user-images.githubusercontent.com/169704/31974534-d5c65f4e-b95e-11e7-9fd4-68b8ae36a346.png)

**Comment by mintty** [comment]
For me, there are 3 slightly tuned shades of grey and a pinkish red. This is not by any means green, yellow, blue or cyan.

**Comment by goreliu** [comment]
I think what themes do is redefining colors.

**Comment by mintty** [comment]
Yes, but within the semantic limits of their names. That's what users expect to be reflected. So the mintty issue quoted above was raised.

**Comment by goreliu** [comment]
I don't know much about themes, in fact I never use them.

**Comment by atgiovannini** [comment]
Maybe can help, I change solarized DARK with other mintty themes, 

[custom-solarized-dark.minttyrc.txt](https://github.com/goreliu/wsl-terminal/files/1427053/custom-solarized-dark.minttyrc.txt)

NOTE: I change append extension .txt, just remove to use it.

**Comment by goreliu** [comment]
@atgiovannini Thanks.
