### ISSUE TITLE
Default shell

### ISSUE THREAD

**Issue by kidpollo** [goreliu/wsl-terminal#53]
Seems that latest Windows 10 update includes `wsl.exe` that does actually honor the default shell used on the ubunty subsystem that I set via the `chsh -s $(which zsh)` command. Is this a feature that can or should be explored? 
Thanks

**Comment by goreliu** [comment]
See alse https://github.com/rprichard/wslbridge/issues/17

**Comment by kidpollo** [comment]
I see I guess then it would possibly come in a future update if wslbridge gets that change.

**Comment by goreliu** [comment]
Yes.

**Comment by goreliu** [comment]
I added a [`tools/6-set-default-shell.bat`](https://github.com/goreliu/wsl-terminal/blob/master/src/tools/6-set-default-shell.bat) script to set the shell in `etc/wsl-terminal.conf` to the default shell in WSL.
