### ISSUE TITLE
typing 'exit' not work sometimes

### ISSUE THREAD

**Issue by sagemind** [goreliu/wsl-terminal#54]
i am used to typing 'exit' to exit wsl-terminal instead of  'Alt+F4' , but sometimes it doesn't work ,  it really disturbs, Could you fix it ? @goreliu

**Comment by goreliu** [comment]
Any error messages? I need more details.

**Comment by sagemind** [comment]
![like this](https://github.com/sagemind/issues/blob/master/1.PNG)

**Comment by sagemind** [comment]
![issue UI](https://github.com/sagemind/issues/blob/master/1.PNG?raw=true)

**Comment by goreliu** [comment]
Will it happen in bash.exe or wsl.exe?

**Comment by goreliu** [comment]
Can you paste last lines of the result of `bash -c "strace -p $(pgrep bash | head -n1)"` in `cmd.exe` when `exit` hanging?

Like this:
```
C:\Users\goreliu>bash -c "strace -p $(pgrep bash | head -n1)"
strace: Process 1603 attached
read(0, "\4", 1)                        = 1
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0

...

rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD TSTP TTIN TTOU], [], 8) = 0
ioctl(255, TIOCSPGRP, [1641])           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
setpgid(0, 1641)                        = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by sagemind** [comment]
![](https://github.com/sagemind/issues/blob/master/2.PNG?raw=true) 
like this?

**Comment by goreliu** [comment]
The left window is wsl.exe? Then you can report this in https://github.com/Microsoft/WSL/issues.

**Comment by sagemind** [comment]
ok, thanks a lot. i will report this .
i testd in two ways: 
open vim in wsl-terminal, then type 'ctrl+z' to exit vim to bash,and type 'exit' twice (just as is shown on above picture), then the terminal is hanging.
 but when i type ':q!' to close vim back to terminal instead , then type 'exit' twice ,the wsl-terminal closed normally.
