### ISSUE TITLE
Share windows enviroment variables with WSL

### ISSUE THREAD

**Issue by atgiovannini** [goreliu/wsl-terminal#55]
I think could be nice to access Windows environment variables from wsl. 

Could be variables starting with prefix WIN_, like $WIN_PATH, $WIN_USERPROFILE, etc...

**Comment by goreliu** [comment]
You can access them with cmd.exe:

```
$ /mnt/c/Windows/System32/cmd.exe /c echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;...
```

**Comment by atgiovannini** [comment]
Yes, I know that but, I hope some solution that reformats output to WSL Path instead Win Path, I mean rewrite `\` to `/` and change drive `C:` to `/mnt/c`

**Comment by goreliu** [comment]
```
win_path_to_wsl_path() {
    driver=$(echo ${1:0:1} | tr 'A-Z' 'a-z')
    other=${1:2}
    echo /mnt/${driver}${other//\\/\/}
}

$ win_path_to_wsl_path "C:\WINDOWS\system32"
/mnt/c/WINDOWS/system32
```
