### ISSUE TITLE
If I pin open-wsl.exe to Taskbar, it always looks for /bin/bash

### ISSUE THREAD

**Issue by randomshinichi** [goreliu/wsl-terminal#56]
In my wsl-terminal.conf I have:
`shell=/usr/bin/zsh`
And it works fine when I double click open-wsl.exe in Explorer. However when I pin it to the taskbar, then when I start the program from there, it always says "can't find /bin/bash".

**Comment by goreliu** [comment]
See also https://github.com/goreliu/wsl-terminal/issues/44

**Comment by goreliu** [comment]
I fixed it in [v0.8.10](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.10).
