### ISSUE TITLE
Add Icon to context menu

### ISSUE THREAD

**Issue by LKS90** [goreliu/wsl-terminal#57]
Hey there!

I thought it would be nice to have a Icon in the context menu. Problem is I don't know how the javascript/registry entry stuff works.

I manually added the Icon Registry entry with the value of the open-wsl.exe to my registry, here is a little preview of how it looks.

![context menu entry with icon](https://i.imgur.com/YmzLJO2.png)

**Comment by LKS90** [comment]
Figured it out!

https://github.com/goreliu/wsl-terminal/pull/58

**Comment by goreliu** [comment]
Thanks.
