### ISSUE TITLE
开启tmux,启动wsl-terminal闪退

### ISSUE THREAD

**Issue by fortystory** [goreliu/wsl-terminal#59]
遇到过两次,都是开机后再启动wsl-terminal的时候窗口一闪就没了.关闭use_tmux再启动正常.之后再修改启动tmux也正常.
wsl-terminal 0.8.5
tmux 2.6

**Comment by goreliu** [comment]
下次可以用 `open-wsl -B "-h err"` 运行，看有什么错误。

**Comment by fortystory** [comment]
@goreliu 好的 加上了 等下次出现

**Comment by fortystory** [comment]
![default](https://user-images.githubusercontent.com/17614043/32639044-e0355bb0-c5fc-11e7-8145-e0a7c0533193.png)

这是wsl自己的问题么

**Comment by goreliu** [comment]
嗯，注销重新登录或者开机后可能出现这个情况，是 WSL 的 bug，已经有人反馈了。

可以在管理员的 cmd 里运行 `net stop LxssManager & net start LxssManager` 来立即恢复，或者等几分钟。

**Comment by fortystory** [comment]
感谢给出解决办法
