### ISSUE TITLE
How to make wstart use linux path 

### ISSUE THREAD

**Issue by alankritjoshi** [goreliu/wsl-terminal#62]
I want to use `cmdtool wstart $filename` where `$filename` represents the relative/absolute linux path of file in `pwd`. However, it seems to want the absolute Windows path of the file. How do I make it work like I want to? I can only think of making a bash function to handle that.

**Comment by goreliu** [comment]
I added a wstartex subcommand https://github.com/goreliu/wsl-terminal/commit/fd9ca6c833746b9f82d437a7f1c641b593da6dfd

Examples:

```
# Open ./etc/themes directory with explorer.exe
$ ./cmdtool wstartex etc/themes

# Open /mnt/c/Windows/win.ini with notepad
$ ./cmdtool wstartex /mnt/c/Windows/win.ini

# Open www.google.com with browser
$ ./cmdtool wstartex www.google.com
```

**Comment by alankritjoshi** [comment]
@goreliu awesome! Thank you for this feature. Can we this in the next release so that `./cmdtool update` works?

**Comment by goreliu** [comment]
Yes, I released [v0.8.7](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.7) just now.

**Comment by alankritjoshi** [comment]
@goreliu that was fast! Thanks! It works except for relative paths or when the absolute path has spaces in them.

For example,

`cmdtool wstartex .`
`cmdtool wstartex /mnt/d/files/a\ directory\ with\ space/a\ file\ with\ space.py`

I can manage this in my zsh though but as an inbuilt feature of `wstartex` would be great.

**Comment by goreliu** [comment]
I will fix it, and I am using this zsh script, it works.

```
#!/bin/zsh

alias run='setsid /init /mnt/c/Windows/System32/cmd.exe /c start'

if [[ $1 == http* || $1 == www* ]] {
    run "" $*
    return
}

dir_name=${1:h}
file_name=${1:t}

if [[ $dir_name == / ]] {
    cd /; run .; cd - >/dev/null
} elif [[ $dir_name == /mnt ]] {
    cd /; run "" $file_name:; cd - >/dev/null
} else {
    shift 2>/dev/null
    cd $dir_name && run "" $file_name $*; cd - >/dev/null
}
```

**Comment by alankritjoshi** [comment]
@goreliu thanks for the fix. It solves my issue :)

**Comment by goreliu** [comment]
I fixed it (https://github.com/goreliu/wsl-terminal/commit/234e3bb3a99c73bfefb0f8ed57889dffb8229a41).

**Comment by alankritjoshi** [comment]
@goreliu  Great! Will pull from the next release

**Comment by alankritjoshi** [comment]
@goreliu did the last change make it into the release?
