### ISSUE TITLE
terminal opens and closes quickly

### ISSUE THREAD

**Issue by vikasrtr** [goreliu/wsl-terminal#63]
Running open-wsl.exe opens and quickly closes terminal within few ms.

I can run 'bash' and it works.
The subsystem have Ubuntu 14.04.

I also tried the steps in #36 
`c:\mine\app\wsl-terminal\bin>wslbridge bash -c pwd`
The output is simply a blank line.

**Comment by vikasrtr** [comment]
For record,  I'm using latest v0.8.6

**Comment by goreliu** [comment]
Will `wslbridge echo abc` work?

```
c:\mine\app\wsl-terminal\bin>wslbridge echo abc & echo %errorlevel%
abc
0
```

**Comment by vikasrtr** [comment]
`wslbridge echo abc` is also not working.  It just shows a blank line as output.

**Comment by goreliu** [comment]
What's the value of `%errorlevel%`?

**Comment by vikasrtr** [comment]
I get the following error code:
`wsl-terminal\bin>echo %errorlevel%`
`9009`

**Comment by goreliu** [comment]
I can't guess the reason, you can report it here (https://github.com/rprichard/wslbridge/issues).

**Comment by vikasrtr** [comment]
@goreliu Sorry my bad.  I was echoing %errorlevel% separately.
The correct output now is as:
`wsl-terminal\bin>wslbridge echo abc & echo %errorlevel%`
`0`
` `

Does it helps now ?

**Comment by goreliu** [comment]
I have no ideas. Maybe you can use [stracent](https://github.com/intellectualheaven/stracent) or [procmon](https://technet.microsoft.com/en-us/library/bb896645.aspx) to look for more details.
