### ISSUE TITLE
Super key doesn't work in wsl-terminal

### ISSUE THREAD

**Issue by Gilbert-Wong** [goreliu/wsl-terminal#64]
Please fix this bug.

**Comment by goreliu** [comment]
I need more details.

**Comment by Gilbert-Wong** [comment]
I have remapped <Super> to <C-c> in my emacs configs. <Super> key Corresponds <menu> in windows and it doesn't work in wsl-terminal .

**Comment by Gilbert-Wong** [comment]
I have remapped <Super> to <C-c> in my emacs configs. <Super> key Corresponds <menu> in windows and it doesn't work in wsl-terminal .

**Comment by goreliu** [comment]
I think Windows ( explorer.exe or other softwares) will catch the `<Super>` key.

**Comment by Gilbert-Wong** [comment]
I suppose `autohotkey` would be helpful.  But I have forgiven to use `<super>` in wsl-terminal. Thanks for reply.
