### ISSUE TITLE
Removing title bar

### ISSUE THREAD

**Issue by shashankgandham** [goreliu/wsl-terminal#66]
Title bar looks ugly especially with the solarized theme, Any way to remove it (especially on full screen) would make it look nice(r)

**Comment by goreliu** [comment]
http://hackerspace.kinja.com/removing-the-windows-title-bar-with-autohotkey-1015709275

**Comment by shillner** [comment]
Just hit [ALT] + [RETURN] and the terminal is displayed in full screen mode without any title bar. This even works with CMD and Powershell

**Comment by goreliu** [comment]
alt + return also works in wsl-terminal.
