### ISSUE TITLE
can't run when pinned to taskbar

### ISSUE THREAD

**Issue by ssshake** [goreliu/wsl-terminal#68]
You get failed to run /bin/bash: no such file or directory. I presume this is because something is a relative path and this breaks when run from the taskbar. This isnt an issue when the executable is run directly from the folder it's in.

You can drag a shortcut onto the task bar, but that breaks the typical 'pin to taskbar' functionality. Mainly, you end up with duplicate items in the task bar (the shortcut icon and the running app)

**Comment by goreliu** [comment]
https://github.com/goreliu/wsl-terminal/issues/44

**Comment by okgolove** [comment]
This solution looks nice, but it would be great if it work without any interventions from outside.

**Comment by goreliu** [comment]
I fix it in [v0.8.9](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.9).

**Comment by okgolove** [comment]
I confirm it works.
