### ISSUE TITLE
McAfee Endpoint Security Marks as a Trojan

### ISSUE THREAD

**Issue by jjuel** [goreliu/wsl-terminal#69]
So don't think this is really an issue, and if it is might not be your issue. Feel free to close it, but this is just sort of a notification. I has just opened open-wsl.exe and all of a sudden it closed and McAfee chirped at me. Well it marked open-wsl.exe as a Trojan. I downloaded straight from this github. So not sure if you can do anything about it or not, but just thought I would let you or others know that your AV might pick it up.

**Comment by DaJakerBoss** [comment]
No Trojan here with Comodo and Windows Defender. Just re-download it for safety.

**Comment by jjuel** [comment]
Can probably close this issue. Our work McAfee marked rustc as a trojan too. I am not sure what their standards are for scanning, but man they are strict.

**Comment by DaJakerBoss** [comment]
You can close it yourself. There's a button.
