### ISSUE TITLE
Hangs changing fonts

### ISSUE THREAD

**Issue by antoniocanas** [goreliu/wsl-terminal#7]
Tried with powerline version of Inconsolata-G and Droid Sans.
It hangs on Options | Text | Apply click.

Latest wsl-terminal on Win 10 Pro

**Comment by goreliu** [comment]
I download `Inconsolata-g for Powerline.otf` from https://github.com/powerline/fonts/blob/master/Inconsolata-g/Inconsolata-g%20for%20Powerline.otf, install it, click Options | Text | Apply, it doesn't hang. What will be happening if you click Save?

**Comment by antoniocanas** [comment]
The same, hangs until I force close it

**Comment by QuiZr** [comment]
Yeah, in latest release (v0.5.1) - Options -> Text -> Select... -> Select whatever font -> Click OK -> Hangs.

**Comment by goreliu** [comment]
@mintty

It seems like a bug of mintty (v2.4.0 v2.4.2 v2.4.3 v2.5.0 with cygwin 2.5.2).

Create a minttyrc like this:

```
Font=Consolas
```

Run mintty, Options -> Text -> Select... ( select a font like DejaVu Sans Mono) -> Apply(A) -> OK, then mintty hangs. Apply(A) and OK are buttons of Fonts dialog.

**Comment by mintty** [comment]
For reference, there had been a font menu crash report previously, see my comment https://github.com/mintty/mintty/issues/533#issuecomment-233146709 about it. In either case, the problem is not reliably reproducible.

**Comment by mintty** [comment]
I have seen font selection hang *occasionally* but also other hangs and even Windows crashes when interacting with WSL. I do not see anything *reproducible* that could be attributed to mintty; as it occurs while the font selection is open, it can as well be a Windows problem.

**Comment by mintty** [comment]
Thanks for closing :) Actually, mintty 2.7.6 does in fact fix a related bug.
