### ISSUE TITLE
Support new type of WSL installation

### ISSUE THREAD

**Issue by mxalbert1996** [goreliu/wsl-terminal#72]
From Windows 10 Fall Creators Update (1709), instead of the lagecy way of installing WSL by `lxrun.exe`, it is recommended to install WSL from Microsoft Store. Currently, wsl-terminal does not run with the new type of WSL installation.
Here's some links that might be useful:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config
https://github.com/hashicorp/vagrant/issues/9298

**Comment by zyx3998970** [comment]
@mxalbert1996 wsl-terminal has supported new type of WSL installation.
You can run tools/write-distro-guids-to-config-file.js to generate the distro_guid config, then open etc/wsl-terminal.conf and uncomment the dirstro_guid line which you preferred to use.

**Comment by mxalbert1996** [comment]
Thanks.
