### ISSUE TITLE
Where to extact / How to save settings?

### ISSUE THREAD

**Issue by jonaskello** [goreliu/wsl-terminal#74]
I extracted wsl-terminal in "C:\Program Files\wsl-terminal". I double-clicked on open-wsl.exe. Next I went to options and set the theme and pressed save. Then I got this error message:

![image](https://user-images.githubusercontent.com/664076/34477851-7bcf13e4-ef9d-11e7-9577-376d15fc0080.png)

My question is how do I save the settings? I guess wsl-terminal is trying to save somehow relative to the dir it started from. So do I have to extract wsl-terminal in / of the wsl filesystem to make it work or is there some other way?

**Comment by shlinux** [comment]
I think this is due to the Windows permission.
You can try install wsl-termianl to other path, such like C:\Users\%username%\AppData\Local\ or D:\Program Files\
