### ISSUE TITLE
wsl-terminal will read and apply Git Bash's .minttyrc

### ISSUE THREAD

**Issue by chenjuntong** [goreliu/wsl-terminal#76]
Normally, wsl-terminal should only read and apply its own configuration, mainly /etc/minttyrc. 
I have installed Git Bash too, which apply its own configuration in path/.minttyrc.
However, I found that when I modify Git Bash's .minttyrc, it acts on wsl-termianl too!
I hope these two mintty can use their own configuration. Is it possible? 
Thank you in advance.😄

**Comment by goreliu** [comment]
What's the path of Git Bash's .minttyrc?
