### ISSUE TITLE
无法正常输入中文

### ISSUE THREAD

**Issue by shlinux** [goreliu/wsl-terminal#77]
64  位 Win10。同样的 mintty 配置，Git Bash 和 wsltty 都可以正常输入中文，但是 wsl-terminal 里不行。

**Comment by chenjuntong** [comment]
请问你的 wsl-terminal 会自动去使用 Git Bash 的 .minttyrc 配置吗？

**Comment by shlinux** [comment]
@chenjuntong 不会啊。

**Comment by chenjuntong** [comment]
@shlinux 我是在系统环境变量中，新建了 HOME ，指向 C:\Home ，里面的 .minttyrc 是给 Git Bash 用的，但是 wsl-terminal 会去读取这个配置；如果去掉了 HOME 系统变量就不会了，不知道你有没有这个情况

**Comment by shlinux** [comment]
@chenjuntong Git Bash 默认的 .minttyrc  不是在用户个人目录中吗？为什么要新建个 HOME 呢？我刚才试了试，Git Bash 会读取 $HOME 里的配置，但是 wsl-terminal 不会啊。我的 wsl-terminal 不是装在系统盘。

**Comment by goreliu** [comment]
wsl-terminal 和 wsltty 用的都是 mintty，不应该有差别，可能是配置的问题。可以把 `etc/minttyrc` 删了重新配置下试试。

**Comment by goreliu** [comment]
如果有问题可以再打开。

**Comment by goreliu** [comment]
@chenjuntong 如果设置了 HOME 变量，就相当于共用环境了。
