### ISSUE TITLE
特殊顏色/字體？ 卡頓嚴重

### ISSUE THREAD

**Issue by xarthurx** [goreliu/wsl-terminal#78]
首先非常感謝做這個項目，比windows 自帶的好太多。

下面說問題：
正常使用的話，換行什麼的稍微有一點點延時。
但如果出現編譯錯誤或者類似問題，錯誤信息會是紅色的，比如這個：
![image](https://user-images.githubusercontent.com/1921878/35640957-05f7bc3c-06bf-11e8-8e94-046f0c2e8247.png)

你可以看到圖裡面兩個換行之間的空間，就是按回車快了一點。
然後換行會非常卡頓，感覺就像一幀一幀的刷新。

這個是字體問題還是顏色或者什麼問題？
很奇怪啊。

**Comment by shlinux** [comment]
我装的 msys2 也存在这个问题。感觉可能是 mintty 和 win10 兼容性问题。

**Comment by goreliu** [comment]
能不能贴一个不依赖环境的脚本，我执行试下。

**Comment by goreliu** [comment]
我这里输出颜色没出现卡顿现象，先关了，其他人如果遇到类似问题可以再打开，并且提供复现方法。
