### ISSUE TITLE
Trojan: Win32/Varpes.M!cl 

### ISSUE THREAD

**Issue by BRAVEMAN-L-BRID** [goreliu/wsl-terminal#8]
im beginner
windows defender alert "Trojan".
is this ok?

**Comment by BRAVEMAN-L-BRID** [comment]
Update windows defender and rescan
it says noproblem. 
sorry
definition of virus : 1.227.2529.0
definition of spyware : 1.227.2529.0

**Comment by gglanzani** [comment]
Had the same issue. Would love to know a bit more about it though!

**Comment by BRAVEMAN-L-BRID** [comment]
Sorry, I dont know of it well. 
Updating def of Windows defender has been eventually in vain.
The defender alert "Trojan" again and deleted the item immediately

Win defender version
def of virus 1.227.2694.0
def of spyware 1.227.2694.0

Now, I use ssh-client "Token2Shell/MD(UWP)" & "wstart" instead of using wsl-terminal. 
and i use Xming with token2shell's X11 Forwarding, and use Background OpenSSH-server in Bash-on-Windows as a windows service.
 it is safety and Comfortable and nice cool design.

**Comment by goreliu** [comment]
All exe files are generated by ahk2exe，ahk (AutoHotkey) is a script language.

**Comment by BRAVEMAN-L-BRID** [comment]
oh, sorry. thanks your info.

the ver0.5.1 has been auto-removed by windows defender.
however, ver0.6.0 is running fine so far.
but I think that it is not a substantive issues. what is the problem here ?
I think windows defender catch open-wsl.exe and alert, using the command bundled with it.

**Comment by gglanzani** [comment]
I've researched it a bit and it indeed seems like a problem with ahk2exe. Sometimes it gets flagged.
