### ISSUE TITLE
duplicated icon on windows 10 taskbar

### ISSUE THREAD

**Issue by xarthurx** [goreliu/wsl-terminal#80]
![image](https://user-images.githubusercontent.com/1921878/35806420-b88a2d58-0a7f-11e8-83ef-b42e60192ec8.png)

which should be in one.

**Comment by zill057** [comment]
There is the answer.
> open-wsl.exe is only a starter of mintty.exe
> https://github.com/goreliu/wsl-terminal/issues/44

**Comment by goreliu** [comment]
I fix it in [v0.8.9](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.9).
