### ISSUE TITLE
input is not a tty

### ISSUE THREAD

**Issue by DrTF** [goreliu/wsl-terminal#81]
git-bash works well, but wsl failed. 

![image](https://user-images.githubusercontent.com/11496772/36064075-8c0c8466-0ec0-11e8-90b2-c09d7147885f.png)
![image](https://user-images.githubusercontent.com/11496772/36064077-96aa0470-0ec0-11e8-9107-51648b1e79ca.png)

**Comment by goreliu** [comment]
You can try `./docker.exe ...` or `/init ./docker.exe`, if it doesn't work, I have no idea.

**Comment by goreliu** [comment]
You can install winpty to wsl-terminal. Download https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-cygwin-2.8.0-x64.tar.gz, put `winpty.dll winpty.exe winpty-agent.exe winpty-debugserver.exe` in `wsl-terminal/bin`, and then use `/init /mnt/c/path/to/wsl-terminal/bin/mintty.exe /bin/winpty.exe ./docker.exe`.

**Comment by DrTF** [comment]
Thanks ! It works.
