### ISSUE TITLE
Way to run it directly in "Bash on Ubuntu on Windows"

### ISSUE THREAD

**Issue by AlesMenzel** [goreliu/wsl-terminal#82]
Hello,
**let me first thank you for this amazing emulator.**

**Question:** Is there a way to run it directly from "Bash on Ubuntu on Windows" with theme (colors, fonts, etc.)?

This is how it looks when opened through `open-wsl.exe` (on the right) vs the default bash on the left.
PS: using the agnoster theme for oh-my-zsh
([Great tutorial on how to change the theme](https://medium.com/@Andreas_cmj/how-to-setup-a-nice-looking-terminal-with-wsl-in-windows-10-creators-update-2b468ed7c326))
![](https://image.prntscr.com/image/YS3INbl7TF6nfSTYTcBlHw.png)

If I change the `.bashrc` to open zsh on startup it has broken colors like:
![](https://image.prntscr.com/image/alAnR231TkqhgKaGqYkH2g.png)

**Comment by ezpuzz** [comment]
First off "Bash on Ubuntu on Windows" is the deprecated version of WSL.  You should uninstall that and use the newer supported version on the Microsoft Store.   After that you should use `chsh` within wsl to set your login shell as `/bin/zsh` then run the `6-set-default-shell` in the `tools` folder inside the wsl-terminal download.  The official `Ubuntu` start menu entry will then open `zsh` in the windows console and `open-wsl.exe` will open `zsh` in mintty.  the file `tools/4-create-start-menu-shortcuts.js` will add a start menu entry for you to open wsl in this mintty which replicates the functionality of the ubuntu shortcut but with a better terminal.

**Comment by AlesMenzel** [comment]
Thanks for the reply, do you happen to know if it is possible to run this shell in VS Code as default shell? If I add the path to open-wsl.exe to VS Code then  it opens new window instead...

**Comment by goreliu** [comment]
You can change the colors here:

![tmp](https://user-images.githubusercontent.com/169704/37339518-df2c59bc-26f5-11e8-8ff8-504af1d70ab9.png)
