### ISSUE TITLE
Paste using CTRL+V

### ISSUE THREAD

**Issue by okgolove-rf** [goreliu/wsl-terminal#84]
How can I configure wsl-terminal to paste using CTRL+V?

**Comment by zill057** [comment]
Try to use ```Ctrl+Shift+V```, it's an alternative for quick pasting.

![image](https://user-images.githubusercontent.com/19730264/37199121-a70db25c-23bb-11e8-8b6f-77563bd23095.png)

**Comment by okgolove** [comment]
It works, thx.
Sometimes `^[[200~` inserting before my clipboard. Any ideas?

**Comment by goreliu** [comment]
You can enable `Ctrl+Shift+letter shortcuts`(https://github.com/goreliu/wsl-terminal/issues/84#issuecomment-371755372) and append this line to `etc/minttyrc`:

```
CtrlExchangeShift=yes
```
Then you can use `Ctrl + c` and `Ctrl + v` to copy and paste.

See also https://github.com/mintty/mintty/issues/524 and https://github.com/mintty/mintty/issues/645.

**Comment by okgolove** [comment]
Yeap, but in this case you'll lose ability to use CTRL+C for SIGINT.
Anyway, thank you!
