### ISSUE TITLE
Missing `i` symbol in filename

### ISSUE THREAD

**Issue by okgolove** [goreliu/wsl-terminal#87]
Hello, I've updated my wsl-terminal to version 0.8.10 a few minutes ago.
And I got next bug:
![image](https://user-images.githubusercontent.com/36846182/37644305-0c8cd66c-2c2c-11e8-9b9e-f36779334075.png)

If you select missed part symbol will appear and stay.
![image](https://user-images.githubusercontent.com/36846182/37644359-381424d4-2c2c-11e8-97a6-5f433ca86091.png)

**Comment by goreliu** [comment]
I seems work well here, I don't how to reproduce it, and I didn't update mintty(v2.8.4) in v0.8.10.

![tmp](https://user-images.githubusercontent.com/169704/37649743-bcae8176-2c6d-11e8-92fa-e67e4018ebef.png)

**Comment by okgolove** [comment]
Another example:
![image](https://user-images.githubusercontent.com/36846182/37654237-1c05f81c-2c4a-11e8-80e7-edb2ad858dfb.png)

I'm not sure but it might be correlated with font (I use Monaco). If I change font to Consolas, it will work ok.
But there wasn't that bug before update.
![image](https://user-images.githubusercontent.com/36846182/37654379-84fe41b2-2c4a-11e8-9784-56d3df84b1d4.png)

**Comment by goreliu** [comment]
You can replace `bin/mintty.exe` with the on from the early wsl-terminal.
