### ISSUE TITLE
删除一些中文符号时，光标的移动距离不正确

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/wsl-terminal#88]
目前发现的有省略号（……）、破折号（——）、单双引号（‘’“”）。
试了各种字体和各种wsl的终端，好像都有问题。

**Comment by goreliu** [comment]
这个我没办法解决。

**Comment by Leoongithub** [comment]
从命令行启动确实没问题了（带上-o FontRender=textout参数），但是怎么把这个选项写到配置里？我尝试把它加到minttyrc或者wsl-terminal.conf的mintty_options里都没有效果。

**Comment by Leoongithub** [comment]
另外透明度选择玻璃时会变成全白，是因为少安装了什么东西吗？

**Comment by goreliu** [comment]
可以加到`mintty_options`里边，我这正常。

```
mintty_options=-o FontRender=textout
```

改成玻璃后得重启下 mintty。

**Comment by Leoongithub** [comment]
按照这个配置试过了也不行，暂时用参数将就一下吧。
另外玻璃这个功能感觉不太好用，窗口后面是白色的话什么都看不清，也不支持获得焦点后变为不透明。

**Comment by goreliu** [comment]
你是不是用 wsl-terminal.lnk 启动的？这个快捷方式是不读配置文件的，要用 open-wsl.exe。

**Comment by Leoongithub** [comment]
不是，我的`wsl-terminal.lnk`的目标是
`D:\wsl-terminal\bin\mintty.exe  --wsl --rootfs=// --configdir "D:\wsl-terminal\etc" -i "D:\wsl-terminal\open-wsl.exe" --option FontRender=textout -t "        " -e /bin/wslbridge  -e SHELL="/bin/bash" -e LANG -t /bin/bash`

**Comment by goreliu** [comment]
这个没问题，那就不知道了。
