### ISSUE TITLE
font rendering different from cmd

### ISSUE THREAD

**Issue by yw662** [goreliu/wsl-terminal#90]
In cmd.exe, consolas
![image](https://user-images.githubusercontent.com/34736747/38073713-31605282-32fa-11e8-8acd-b7ca06bde273.png)

In wsl-terminal, consolas
![image](https://user-images.githubusercontent.com/34736747/38073829-9e56ff26-32fa-11e8-9782-fa4b2a17be10.png)

![image](https://user-images.githubusercontent.com/34736747/38073771-6a56195a-32fa-11e8-96c4-2eebd373e33e.png)

The font and size is the same but the rendering is different.

**Comment by goreliu** [comment]
Yes.
