### ISSUE TITLE
[Bug] 运行aptitude、mc等程序时字符显示有问题

### ISSUE THREAD

**Issue by lgwangh** [goreliu/wsl-terminal#91]
在运行aptitude、mc等等占据整个终端界面的程序时，字符错乱
![wsl_terminal_aptitude1](https://user-images.githubusercontent.com/19831228/38139109-9e16a2de-3460-11e8-847e-18d26c6f0adc.png)
![wsl_terminal_aptitude2](https://user-images.githubusercontent.com/19831228/38139115-a3e2f366-3460-11e8-8a71-41bf9a6a4052.png)
看起来是“—”符号的长度不对，我不知道还有没有其他类似的字符问题。
我的字体配置是这样的：
```
BoldAsFont=no
FontHeight=10
Font=Inziu Iosevka Slab SC
Scrollbar=none
Term=xterm-256color
CursorType=block
AllowBlinking=yes
Locale=zh_CN
Charset=UTF-8
BellType=0
BellTaskbar=no
Printer=*
Language=@
```
我尝试过更换其他中文字体，但是没有解决问题。

**Comment by goreliu** [comment]
我这里没有问题，你试下在 wsl.exe 里正常不。

**Comment by lgwangh** [comment]
之前一直在用wsl.exe，同样的字体，是正常的。刚截的图：
![2018_03_31-001](https://user-images.githubusercontent.com/19831228/38158298-2abaf90c-34c4-11e8-9016-e62c57565184.png)

**Comment by goreliu** [comment]
无法复现。
