### ISSUE TITLE
敲命令总会重复第一个字符

### ISSUE THREAD

**Issue by leibnizl** [goreliu/wsl-terminal#94]
如图所示
![0](https://user-images.githubusercontent.com/11663134/38487701-a6e26c76-3c13-11e8-9e91-f1b726bf0538.png)
在wsl中输入的第一个字符总会重复，而且前面的字符不能删除。

**Comment by goreliu** [comment]
把 .bashrc 或者 .zshrc 清空后再试试呢？应该是配置文件的问题。

**Comment by goreliu** [comment]
和 wsl-terminal 无关，我先关了，如果还有问题可以再继续。
