### ISSUE TITLE
Can't type anything

### ISSUE THREAD

**Issue by YXuewei** [goreliu/wsl-terminal#96]
after open terminal, won't be able to type anything into console.
When press a key, cursor won't blink, but nothing came out. 
Tried re-download and replace any existing file, won't work

**Comment by YXuewei** [comment]
Yes, wsl itself works perfectly fine. Just open-wsl have this problem, it will load into zsh, but after that, I can't input anything. Tried to alter encoding from UFT-8 to others and switch back, not working, tried to change my input language other than English, nor working, tried change non-unicode language setting, still not working,.

**Comment by goreliu** [comment]
Is `bin/wslbridge.exe` working?

**Comment by YXuewei** [comment]
No, bin\wslbridge.exe is not working， it's loaded into zsh, but still, can't input anything
When I try to open bin\mintty.exe, it says : Failed to run '/bin/bash': No such file or directory

**Comment by goreliu** [comment]
Than you can try `bin\wslbridge.exe -t bash` or `bin\wslbridge.exe -t vim`.

**Comment by goreliu** [comment]
You can clear ~/.zshrc, and add contents to it.

**Comment by YXuewei** [comment]
tried remove and re-install zsh, rewrite zshrc, set bashrc to default. reinstalled WSL-Terminal, none of them were working. I had to give up on it and get back into windows command prompt default shell.
