### ISSUE TITLE
Opening terminal takes long time and throws error

### ISSUE THREAD

**Issue by DanielGGordon** [goreliu/wsl-terminal#97]
Sorry not the best title but that's the issue.

### My setup:
I had the beta version installed of WSL. I recently got the creator's edition update and I uninstalled WSL and re-installed using the Microsoft Store. Then I downloaded wsl-terminal. When I try to open `open-wsl.exe` from explorer, it takes about **40 seconds to load**.

I then get an error message with the first line:
`wslbridge warning: process didn't exit after 10 seconds: "C:\Users\gordon\Downloads\software\wsl-terminal\bin\wslbridge.exe" --press-return 476`

Loading the default terminal is snappy (less than 1 second). I downloaded wsl onto my main drive which is NTSF so that shouldn't be an issue.

**Comment by DanielGGordon** [comment]
![image](https://user-images.githubusercontent.com/11824880/39200861-f0cb916e-47b2-11e8-90d7-390dd6b4e6f5.png)

**Comment by goreliu** [comment]
After installing a distro using the Microsoft Store, it will take a while when you first use it (run ubuntu.exe or wsl.exe).

**Comment by DanielGGordon** [comment]
That is just the first time - this happens every time.

**Comment by DanielGGordon** [comment]
Ok so maybe you are right... I am not getting that super long delay anymore!
