### ISSUE TITLE
‘1-add-open-wsl-terminal-here-menu’ not usable on Win10

### ISSUE THREAD

**Issue by ybj14** [goreliu/wsl-terminal#99]
Thank you for this neat terminal! However, after executing `1-add-open-wsl-terminal-here-menu.js` , I have got `Open wsl-terminal Here` in the menu, but after clicking that option `Explorer.EXE` tells me `Application not found`. I have tried to add path of `open-wsl.exe` to PATH environment variable, but it's of no help.

**Comment by goreliu** [comment]
What's the path of `open-wsl.exe`?

**Comment by ybj14** [comment]
For me it's `D:\Download\wsl-terminal-0.8.11\wsl-terminal\open-wsl.exe`

**Comment by ipcjs** [comment]
把`Microsoft (R) Windows Based Script Host`设为js文件的默认打开方式，再双击运行，就可以了

**Comment by ybj14** [comment]
I checked the registry and found `1-add-open-wsl-terminal-here-menu` add `C:\Windows\open-wsl.exe` to the registry instead of  `D:\Download\wsl-terminal-0.8.11\wsl-terminal\open-wsl.exe`. The problem was solved after I manually changed it.

**Comment by HopeForToday** [comment]
@ybj14 You must set `Microsoft (R) Windows Based Script Host` as default open program, rather than just open it with `Microsoft (R) Windows Based Script Host`.
